version: "3.8"

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DISABLED: "false"
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
